# Minecraft SMP — server.properties
# Copiat automat în data/ la primul start de itzg/minecraft-server

online-mode=true
difficulty=normal
gamemode=survival
spawn-protection=16
view-distance=8
simulation-distance=6
max-players=30
max-tick-time=60000
network-compression-threshold=256
enable-rcon=true
rcon.port=25575
white-list=false
enforce-whitelist=false
pvp=true
allow-flight=false
